using System;
using System.Collections.Generic;

namespace BIW_KSOA_Interface.Models
{
    public partial class mchk
    {
        public string dwbh { get; set; }
        public string danwbh { get; set; }
        public string dwmch { get; set; }
        public string zjm { get; set; }
        public string kemuhao { get; set; }
        public string ywy { get; set; }
        public string kehufl { get; set; }
        public string quyufl { get; set; }
        public string kehulb { get; set; }
        public string isjh { get; set; }
        public string isxs { get; set; }
        public string shh { get; set; }
        public string dzhdh { get; set; }
        public string yhzhh { get; set; }
        public string lxr { get; set; }
        public string zipno { get; set; }
        public string kehudengji { get; set; }
        public string lxrdh { get; set; }
        public Nullable<decimal> ghxde { get; set; }
        public Nullable<decimal> xsxde { get; set; }
        public Nullable<int> otd { get; set; }
        public Nullable<int> xdqxg { get; set; }
        public Nullable<int> xdqxx { get; set; }
        public Nullable<decimal> koul { get; set; }
        public Nullable<decimal> canskl { get; set; }
        public Nullable<decimal> yshye { get; set; }
        public Nullable<decimal> yfye { get; set; }
        public Nullable<decimal> yingshsx { get; set; }
        public Nullable<decimal> yshjzh { get; set; }
        public Nullable<decimal> yfjzh { get; set; }
        public string beactive { get; set; }
        public string oldcode { get; set; }
        public string yishj { get; set; }
        public string xvkz { get; set; }
        public string shfyyzz { get; set; }
        public string yingyzz { get; set; }
        public string jingyfw { get; set; }
        public string hangymch { get; set; }
        public Nullable<decimal> oldyfye { get; set; }
        public Nullable<decimal> oldyshye { get; set; }
        public string frdb { get; set; }
        public Nullable<decimal> zhgzsh { get; set; }
        public Nullable<decimal> zhj_bl { get; set; }
        public Nullable<decimal> shn_xshe { get; set; }
        public string heshitg { get; set; }
        public Nullable<decimal> pzhshl { get; set; }
        public string zhj_dh { get; set; }
        public string is_zhdshg { get; set; }
        public string zjxpzh { get; set; }
        public string is_pxrz { get; set; }
        public string is_wf { get; set; }
        public string zhuypzh { get; set; }
        public string is_xkz { get; set; }
        public string is_yyzz { get; set; }
        public string is_shqwtsh { get; set; }
        public string is_shgzh { get; set; }
        public string is_shfzh { get; set; }
        public string is_lxdh { get; set; }
        public string is_zhlbzhxy { get; set; }
        public string is_jq { get; set; }
        public string is_gb { get; set; }
        public string is_jg { get; set; }
        public string qita { get; set; }
        public string bmyj { get; set; }
        public string zhj_yj { get; set; }
        public string zhgshp { get; set; }
        public string tbrq { get; set; }
        public string zhlfzr { get; set; }
        public Nullable<decimal> shn_hgl { get; set; }
        public string culture { get; set; }
        public string zhibumen { get; set; }
        public string shenhrq { get; set; }
        public string xkzyxq { get; set; }
        public string gspzsyxq { get; set; }
        public string gmpzsyxq { get; set; }
        public string khyh { get; set; }
        public string dzdh { get; set; }
        public string psdzm { get; set; }
        public string lastmodifytime { get; set; }
        public string czcaozy { get; set; }
        public string idcard { get; set; }
        public string xvkzname { get; set; }
        public string fzhjg { get; set; }
        public string fzhrq { get; set; }
        public string yyzzdjjg { get; set; }
        public Nullable<decimal> reg_capital { get; set; }
        public string shwdjh { get; set; }
        public string jyfsh { get; set; }
        public string zlzhshbh { get; set; }
        public string limitTime { get; set; }
        public Nullable<decimal> gonghnl { get; set; }
        public string gmpzsh { get; set; }
        public string faxno { get; set; }
        public Nullable<decimal> yusye { get; set; }
        public Nullable<decimal> yufye { get; set; }
        public Nullable<decimal> flye { get; set; }
        public string yyzzyxq { get; set; }
        public Nullable<int> chnjsts { get; set; }
        public string jsfs { get; set; }
        public string zhangq { get; set; }
        public string fkfs { get; set; }
        public string qyzg { get; set; }
        public string qyxy { get; set; }
        public string rshtqx { get; set; }
        public string heth { get; set; }
        public string zljryy { get; set; }
        public string zljjyy { get; set; }
        public string htzht { get; set; }
        public string htlx { get; set; }
        public string is_dujia { get; set; }
        public string htkshrq { get; set; }
        public string htjshrq { get; set; }
        public string phje { get; set; }
        public string flshj { get; set; }
        public string flrwl { get; set; }
        public string fle { get; set; }
        public string flzfshj { get; set; }
        public string fltj { get; set; }
        public string fylx { get; set; }
        public string fye { get; set; }
        public string fyzfshj { get; set; }
        public string beizhu { get; set; }
        public string is_thh { get; set; }
        public string yyzznjnf { get; set; }
        public string frsqwtsyxq { get; set; }
        public string bwtr { get; set; }
        public string bwtrsfzyxq { get; set; }
        public string zlbzxysyxq { get; set; }
        public string ypscpjyxq { get; set; }
        public string yjjk_dwbh { get; set; }
        public string yjjk_dwmch { get; set; }
        public string zzjgdmz { get; set; }
        public string is_wlgs { get; set; }
        public string caozy { get; set; }
    }
}
